### ISSUE TITLE
SDR++ Headless Mode

### ISSUE THREAD

**Issue by lwvmobile** [AlexandreRouma/SDRPlusPlus#1063]
I looked to see if this was already requested, or mentioned, but couldn't find anything in issues or projects, so I apologize if this has already been asked.

How about a feature similar to the SDR++ server mode, but instead of it being a server for other SDR++ clients to connect to, its just a headless instance of SDR++ started up with the same parameters as was last set in its graphical interface and the last device already started. Optionally, it could also have a few extra CLI switches for listing connected devices, selecting device to use and start up, and enable certain features like the Audio Network Sink, RigCTL server, etc.

Reasoning: To be able to run an instance of SDR++ on a remote SSH instance or similar without needing a desktop remote, or to run on lower powered or older machines that can't handle the load of the graphical elements as well (OpenGL Waterfall, etc).

**Comment by AlexandreRouma** [comment]
Hi,

This would require completely redoing every part of the app and needlessly cluttering the code to allow for GUI options to be controlled from the command line. SDR++ was always designed from the start as a GUI app with all parts of the code directly creating their own menus. Server mode is able to get away with running headless since basically every part of the app is shut off except the module loader and a special source module GUI abstraction is used. And even if you could, the insane number of command line flags needed to control every option of every module would just get ridiculous.

> To be able to run an instance of SDR++ on a remote SSH instance or similar without needing a desktop remote.

Nothing stops you from doing that. You can use SDR++ server (recommended) or use SSH X forwarding to have the window appear on your client.

> run on lower powered or older machines that can't handle the load of the graphical elements as well (OpenGL Waterfall, etc).

The load of these elements is nothing compared to the power needed for DSP. If your target machine can't handle the GUI, it's probably time to use something else for SDR.

If you really need something headless, using the DSP library directly from a C++ custom program or using rtl_fm is probably a better option.
