### ISSUE TITLE
Incorrect equation to get samples from RTL-SDR

### ISSUE THREAD

**Issue by JVital2013** [AlexandreRouma/SDRPlusPlus#1260]
**Hardware**
- CPU: Intel Core i5-6600K
- RAM: 16GB
- GPU: Radeon RX 580
- SDR: Local Nooelec NESDR SMArTee XTR SDR, and Nooelec NESDR SMArt v5 SDR (should be all RTL-SDR based dongles)

**Software**
- Operating System: Ubuntu 22.04 (or any OS; bug in source)
- Built against 794d6ff

**Bug Description**
In the following files:

- `source_modules/rtl_sdr_source/src/main.cpp`
- `source_modules/rtl_tcp_source/src/rtl_tcp_client.cpp`

The equation to take samples from the dongle and write them to `stream->writeBuf` is incorrect. The correct equation is (paraphrasing variable names here): 

```cpp
for (int i = 0; i < sampCount; i++) {
    _this->stream.writeBuf[i].re = (float)(buf[i * 2] - 127.4f) / 128.0f;
    _this->stream.writeBuf[i].im = (float)(buf[(i * 2) + 1] - 127.4f) / 128.0f;
}
```

The difference is the `127.4f` part, which you have as 127 or 128 depending on the source file. The incorrect equation results in a DC spike that is larger than it should be. Here are my sources for this change:

- https://cgit.osmocom.org/gr-osmosdr/commit/?id=0edfcfcba0ddf0fd5002dab70331d75a376bcf3f
- https://cgit.osmocom.org/gr-osmosdr/tree/lib/rtl/rtl_source_c.cc#n177
- https://github.com/pietern/goestools/blob/865e5c73683f8f688d102748e6b495ab5978768f/src/goesrecv/rtlsdr_source.cc#L164 (he refactored the equation strangely, but the math still works out the same)

SatDump has also been changed to this equation to a good effect.

**Steps To Reproduce**
1. Use any RTL-SDR and observe the DC spike
2. Make the suggested code change, and see the spike has gone away/been reduced, without using IQ correction

**Before**
![before](https://github.com/AlexandreRouma/SDRPlusPlus/assets/24253715/8c902c5f-235d-4fea-be51-eddb4aef1d96)

**After**
![after](https://github.com/AlexandreRouma/SDRPlusPlus/assets/24253715/6add9ea1-e23d-40a4-a147-4161bf296f43)

**Comment by AlexandreRouma** [comment]
This is not as clear cut as you make it out to be. I have collected the data of offset vs amplitude for 7 RTL-SDR dongles (3x RTL-SDRblog v4, 2x RTL-SDRblog v3, NESDRsmart and NESDRsmart XTR). This reveals that the offset is dependent on the amplitude for most modern dongles and can be quite random for older ones. Below is the raw data table and a graph representing the offset (from 127) as a function of IQ amplitude.

![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/33daef6a-c373-43df-a36a-e424330dfd8a)
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/b58669f3-394b-459e-a0ff-d432b1fc5824)

Calling the equation used "wrong" is rather silly. This equation has been traditionally used in most other RTL-SDR supporting software because that's just how uint8 samples are encoded.

**Comment by AlexandreRouma** [comment]
After some more statistical testing, it seems the offset is indeed mostly 0.4
![image](https://github.com/AlexandreRouma/SDRPlusPlus/assets/17126412/3e86eb7f-5d4b-47c5-8da8-3eb001f0932b)

I'll implement the modification
