### ISSUE TITLE
Chinese support plan?

### ISSUE THREAD

**Issue by EeeLo** [AlexandreRouma/SDRPlusPlus#1345]
**Feature description**
Thanks for your greate software!
More better by Chinese support for HAM!

**Comment by AlexandreRouma** [comment]
I'm not sure what this is asking for?

**Comment by damp11113** [comment]
> I'm not sure what this is asking for?

I think he want Chinese lang for this

**Comment by Mr-Precise** [comment]
Hmm, I think a localization system would be useful.
About 60% of the interface can be translated

**Comment by EeeLo** [comment]
> I'm not sure what this is asking for?

Yes, I want Chinese lang version,that's will be very friendly for us, thanks.

**Comment by AlexandreRouma** [comment]
Internationalization is not planned. Not only is having to have all the strings of the software in a file instead of the code itself make the UI code less readable, but internationalization involves more than simply translating each bit of text which is just an all around nightmare.

For the record, English is not my native language either (I'm from a country that speaks french), but it will be the only language SDR++ will use.

**Comment by damp11113** [comment]
imgui font issue?
