### ISSUE TITLE
Fobos SDR support

### ISSUE THREAD

**Issue by rigexpert** [AlexandreRouma/SDRPlusPlus#1448]
Ready to add a Fobos SDR support to SDR++

**Comment by rigexpert** [comment]
https://github.com/rigexpert/SDRPlusPlus

**Comment by AlexandreRouma** [comment]
I don't support hardware that I don't physically have. As already discussed with other similar requests in the past, I take responsibility for declaring hardware as supported because I am the one receiving support requests from users. I also have to maintain the code through versions. I can't possibly do that without being able to test myself.
