### ISSUE TITLE
[FEATURE REQUEST] Frequency Scanner.

### ISSUE THREAD

**Issue by grappas** [AlexandreRouma/SDRPlusPlus#299]
It would be nice if there was some of that feature - at least based on bookmarks if not scanning whole bandwidth.

**Comment by JosephTheTank13** [comment]
I second this!

**Comment by AlexandreRouma** [comment]
A frequency scanner feature is already in the works, you can actually already see the `scanner` folder in the source code

**Comment by AlexandreRouma** [comment]
I'll update this thread once the feature is properly implemented

**Comment by grappas** [comment]
It would be nice if it been implemented like original Frequency Scanner plugin in SDR#

**Comment by jaymot123** [comment]
I came here to request this and it's already in the works. Great news.

**Comment by perseus68-github** [comment]
Definitely a"must have" for any top-rated SDR software. Can't wait to see it implemented 👌

**Comment by grappas** [comment]
@AlexandreRouma If I may - you said "once the feature is properly implemented" - even if It isn't (as you said) "properly" implemented but implemented nonetheless: Is there any way to activate it or test it. I'm using aur package and if it picks code straight from main repo, than it should be some way to test it right?

**Comment by AlexandreRouma** [comment]
there's just the skeleton of the module but it doesn't do anything

**Comment by Wnfidencio** [comment]
I think good changes to the SDR# frequency scanner would be to put a schedule, so the radio changes what it's scanning accordingly. Also clarify the threshold levels that the red and yellow lines represent, letting the user choose which SNR he wants to use in a box.
I believe that the scanner must have a list of canceled frequencies, and that this list can be downloaded and edited in other software, or in SDR++ itself, so that we can easily add and remove frequencies from this blacklist.
I believe that the scanner doesn't make sense without an audio recorder, which could also be improved and facilitated, especially in the matter of how to save file names. And also create a log of recorded audio where the user can launch other features of that signal and download everything in a .csv for example.

**Comment by Wnfidencio** [comment]
I think that just one plugin could just concatenate the functions of Frequency Scanner, Frequency manager and Audio Recorder with the addition of a scheduler and more signal classification options.

**Comment by BT-Justice** [comment]
> I'll update this thread once the feature is properly implemented

Hopefully soon.  Miss using my Airspy as a scanner.

**Comment by icepicknz** [comment]
interested too; something to scan a group loaded from frequency manager

**Comment by gbeyer3** [comment]
Hi, I'm not seeing a scanner folder in the source code per 8/222/21 post by Alexandre.  Am I missing something?  Thanks.

**Comment by grappas** [comment]
I've bumped recently on that scanner module for gqrx. Made myself a simple modification (that yellow an red line from airspy ;))

https://github.com/neural75/gqrx-scanner/pull/20

That on linux it's not all lost ;)

**Comment by AlexandreRouma** [comment]
Added and available in the latest nightly, development will continue.

**Comment by grappas** [comment]
But there's no bookmark scanner 😒

**Comment by grappas** [comment]
😥
