### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 3Domse3** [AlexandreRouma/SDRPlusPlus#663]
- recording audio and baseband simultaneously
- baseband replay controls for scrubbing and pausing and recording info view with length, frequency etc

**Comment by AlexandreRouma** [comment]
1) Just add a second recorder instance and start both (Module Manager -> select "recorder" in the drop down at the bottom -> give it a name like "Recorder 2" in the text field next to the drop down -> press "+"
2) Already requested and planned

**Comment by AlexandreRouma** [comment]
whoops wrong button, wil close once the n°2 is available

**Comment by 3Domse3** [comment]
Oh wow! I didn't know SDR++ was so customizable :D Thanks for the tip!

**Comment by 3Domse3** [comment]
Some more ideas:
- make bookmarks editable with right click on their label 
- add a searchbar for finding bookmarks

**Comment by 3Domse3** [comment]
And more:
- make bookmark colors and/or category colors changeable

**Comment by 3Domse3** [comment]
- make sliders scrollable with mousewheel

**Comment by 3Domse3** [comment]
- make baseband recording bandwidth selectable

**Comment by shuyuan-liu** [comment]
Thanks @3Domse3 for the suggestions. I'd suggest splitting them into separate Issues, maybe grouping the bookmark-related features together, because this thread can get difficult to manage with so many points. I think it will be easier to track progress and discuss each feature in its own Issue than in a single list.

**Comment by 3Domse3** [comment]
Will do :)
