### ISSUE TITLE
libvolk.so.1.4 not found

### ISSUE THREAD

**Issue by Francky46** [AlexandreRouma/SDRPlusPlus#78]
>`sdr@sdr:~/sdr$ sdrpp
sdrpp: error while loading shared libraries: libvolk.so.1.4: cannot open shared object file: No such file or directory
`
> OS :  Ubuntu 20.04.2 LTS

Hello, I used the dpkg method with the .deb of the version "SDR ++ v0.2.5_beta PREVIEW # 3".
sdrpp cannot find libvolk although it was installed from the canonical repository, then from source "libvolk.so.1.4" directly. Nothing helps, it still doesn't work.

Is this a known issue? Thanks

**Comment by AlexandreRouma** [comment]
Hello,
This is a known issue. Debian and Ubuntu 18.04 have volk 1 while Ubuntu 20.04 has volk 2.

I recommend building the latest commit instead of installing from the deb. As you already have all the dependencies installed, it should be relatively easy:

First, make sure you uninstall the version you installed with the deb, next:
```
git clone https://github.com/AlexandreRouma/SDRPlusPlus
cd SDRPlusPlus
mkdir build
cd build
cmake ..
make -j$(nproc)
sudo make install
```
