### ISSUE TITLE
AUR's PKGBUILD has a broken pkgver()

### ISSUE THREAD

**Issue by drws** [AlexandreRouma/SDRPlusPlus#902]
**Software**
- Operating System: Arch Linux

**Bug Description**
The `pkgver()` in `PKGBUILD` is broken. What it returns confuses AUR helpers and triggers unneeded updates. Please see the latest comments (which also provide a solution) [in the AUR](https://aur.archlinux.org/packages/sdrpp-git).

**Steps To Reproduce**
1. install SDR++ from AUR
2. check for updates with an AUR helper
3. an update for `sdrpp-git` is found (even though it shouldn't be)

**Comment by AlexandreRouma** [comment]
The AUR package will no longer be supported since the AUR admin decided to give away the package to someone else due to not fixing this versioning quirk (which i'll add was still up to previous recommendations for git packages).

I recommend you instead switch to building from source as no support in any way shape or form will be given to the AUR package and it will predictably start (already has actually) deviating from the official module set.
